### PR TITLE
GH-62: Feature; Added "back" button for NPC Attack Frame

### PR DESCRIPTION
**Pull request by y345-git**
Added a "back" button once you attack a NPC and also made the NPC tab update values of the lost troops.
image
image
image

* Issue: gh-62

### CODE REVIEW

**Review by ItsNeil17 — CHANGES_REQUESTED** [review]
set the value for all IntegerOnlyInput(s) to `0`

**Comment by y345-git** [comment]
> set the value for all IntegerOnlyInput(s) to `0`


> I have made the requested changes; please review again

**Comment by Owen-Griffin** [comment]
LGTM

**Review by Owen-Griffin — APPROVED** [review]
LTGM

**Comment by Owen-Griffin** [comment]
Tested, please merge @ItsNeil17

**Pull request merged**
