### PR TITLE
Sync Fork

### PR DESCRIPTION
**Pull request by Were-Woof**
Review individual commits in order to see changelog

### CODE REVIEW

**Comment by ItsNeil17** [comment]
UI needs to be designed. It would be great if someone were to be able to get a template of the UI done & we'll fill it in with the db queries later.

**Comment by ItsNeil17** [comment]
@Were-Woof can you also list other stuff that's left?

**Comment by y345-git** [comment]
> UI needs to be designed. It would be great if someone were to be able to get a template of the UI done & we'll fill it in with the db queries later.

I gotchu 😉

**Comment by ItsNeil17** [comment]
I have created a project & issues on the information above. 

Refer:

- #5 
- #6 
- #7 
- #8 
- [Project Will of Steel App](https://github.com/orgs/WillofSteel-Devs/projects/2/views/2?sliceBy%5Bvalue%5D=Iteration+1)

**Pull request merged**
